Add User model, sample data, and tests
Twaha-Rahman/e-commercify pull request #110
Opened 2020-08-10 16:51 UTC by snowteamer

**Description**

This changeset includes three new files, namely;

- Some minimal sample user data in sampleUserData.js. It has values only for required fields.
- The associated Mongoose schema and model.
  Currently it defines a simple string `password` field so as to minimize merge conflicts with the coming auth implementation, but of course it will have to be redefined as a strongly encrypted password as soon as possible.
- A corresponding Jest test file.
I've given my own style to this file since I wanted to experiment a bit with Jest, so it is currently inconsistent with respect to the other test files. But it shouldn't be difficult to modify it to match the other files if needed.

2020-08-11 08:57 UTC, Twaha-Rahman requested changes
We need some changes here and there. other than that, looks promising!

2020-08-11 08:57 UTC, Twaha-Rahman commented on src/schemas/db/userSchema.js
> +    },
Let's be more explicit here:

```suggestion
    linkedCompanyId: {
      type: ObjectID,
      required: false
    },
```

2020-08-11 08:57 UTC, Twaha-Rahman commented on src/schemas/db/userSchema.js
> +    },
Again... let's be explicit ->

```suggestion
    refreshToken: {
      type: String,
      required: false
    },
```

2020-08-11 08:57 UTC, Twaha-Rahman commented on tests/userModel.test.js
> +const validUserData = JSON.parse(JSON.stringify(sampleUserData));
Umm.... why are you deeply copying here?

2020-08-11 08:57 UTC, Twaha-Rahman commented on tests/userModel.test.js
> +      );
This looks a bit verbose. Let's simplify it like so:

```suggestion
     const validateIncompleteUserData = incompleteUser.validate();
     
      await expect(validateIncompleteUserData ).rejects.toThrow(
        mongoose.Error.ValidationError
      );
```

2020-08-11 08:57 UTC, Twaha-Rahman commented on tests/userModel.test.js
> +
Add another test that adds the optional fields and checks if the optional fields were set.

2020-08-11 08:57 UTC, Twaha-Rahman commented on tests/userModel.test.js
> +  it.each(['email', 'password', 'userName'])(
Maybe add a link to the doc for the `it.each` here.

2020-08-12 14:34 UTC, snowteamer commented on tests/userModel.test.js
> +const validUserData = JSON.parse(JSON.stringify(sampleUserData));
Well because the ´permissions´ field is an object. And also because I saw that you did the same

2020-08-12 14:50 UTC, snowteamer commented on tests/userModel.test.js
> +      );
Is it really less verbose? It's no big deal, but we now have more lines, more tokens, and a new variable

2020-08-12 17:10 UTC, snowteamer commented on tests/userModel.test.js
> +  it.each(['email', 'password', 'userName'])(
Ok but I think it was not really needed, since it is just normal usage of a regular Jest function.

2020-08-14 07:29 UTC, Twaha-Rahman commented on tests/userModel.test.js
> +      );
Okay. Let's leave it as it is.

2020-08-14 07:34 UTC, Twaha-Rahman commented on tests/userModel.test.js
> +const validUserData = JSON.parse(JSON.stringify(sampleUserData));
I deeply copied because I was modifying the `object` by deleting `key`s.

Since you're not modifying the object, I don't think deeply copying here is necessary. If you need to modify the `sampleUserData`, then I think deep copying will be needed.

2020-08-14 13:19 UTC, snowteamer commented on tests/userModel.test.js
> +const validUserData = JSON.parse(JSON.stringify(sampleUserData));
Indeed I thought we might need the ability to modify the object later, e.g. when we switch to a schema with an encrypted password field. 
But if you prefer that we just shallow copy for now and switch to cloning only when needed, that's fine too

2020-10-23 01:51 UTC, closed without merging